// Enums
export {
  BankId,
  BankNames,
  BankMortgageUrls,
  BankSavingsUrls,
  MortgageType,
  CurrencyIndex,
  Segment,
  Channel,
  SourceType,
  ExtractionMethod,
  MortgageScenarioKey,
  SavingsAccountType,
  // Savings segmentation enums
  SavingsBalanceTier,
  SAVINGS_BALANCE_THRESHOLDS,
  SavingsBankType,
  BankTypeClassification,
  SavingsScenarioKey,
} from "./enums.js";

// Types
export type {
  CopFixedRate,
  UvrSpreadRate,
  Rate,
  PayrollDiscount,
  OfferConditions,
  ExtractionInfo,
  OfferSource,
  MortgageOffer,
  RankingMetric,
  RankedEntry,
  RankedGroup,
  ScenarioRanking,
  MortgageRankings,
  MortgageOffersDataset,
  BankMortgageParseResult,
  // Savings types
  SavingsRate,
  ScrappedSavingsSource,
  ManualSavingsSource,
  SavingsSource,
  SavingsOffer,
  SavingsOffersDataset,
  BankSavingsParseResult,
  // Savings rankings types
  SavingsRankingMetric,
  SavingsRankedEntry,
  SavingsRankedGroup,
  SavingsScenarioRanking,
  SavingsRankings,
  // Rate history types
  MortgageHistoryPoint,
  MortgageRateHistory,
  SavingsHistoryPoint,
  SavingsRateHistory,
} from "./types.js";

// Rate history helpers
export {
  deriveMortgageSeriesKey,
  deriveSavingsSeriesKey,
  mortgageRateKey,
  savingsRateKey,
  mortgagePlotValue,
  savingsPlotValue,
  groupMortgageHistory,
  groupSavingsHistory,
} from "./history.js";
export type { RateSeries } from "./history.js";

// Zod Schemas
export {
  BankIdSchema,
  MortgageTypeSchema,
  CurrencyIndexSchema,
  SegmentSchema,
  ChannelSchema,
  SourceTypeSchema,
  ExtractionMethodSchema,
  MortgageScenarioKeySchema,
  SavingsAccountTypeSchema,
  CopFixedRateSchema,
  UvrSpreadRateSchema,
  RateSchema,
  PayrollDiscountSchema,
  OfferConditionsSchema,
  ExtractionInfoSchema,
  OfferSourceSchema,
  MortgageOfferSchema,
  RankingMetricSchema,
  RankedEntrySchema,
  RankedGroupSchema,
  ScenarioRankingSchema,
  MortgageRankingsSchema,
  MortgageOffersDatasetSchema,
  BankMortgageParseResultSchema,
  // Savings schemas
  SavingsRateSchema,
  ScrappedSavingsSourceSchema,
  ManualSavingsSourceSchema,
  SavingsSourceSchema,
  SavingsOfferSchema,
  SavingsOffersDatasetSchema,
  BankSavingsParseResultSchema,
  // Savings rankings schemas
  SavingsScenarioKeySchema,
  SavingsBalanceTierSchema,
  SavingsBankTypeSchema,
  SavingsRankingMetricSchema,
  SavingsRankedEntrySchema,
  SavingsRankedGroupSchema,
  SavingsScenarioRankingSchema,
  SavingsRankingsSchema,
  // Rate history schemas
  MortgageHistoryPointSchema,
  MortgageRateHistorySchema,
  SavingsHistoryPointSchema,
  SavingsRateHistorySchema,
} from "./schemas.js";
