// Enums
export {
  BankId,
  BankNames,
  BankUrls,
  BankMortgageUrls,
  BankSavingsUrls,
  MortgageType,
  CurrencyIndex,
  Segment,
  Channel,
  SourceType,
  ExtractionMethod,
  MortgageScenarioKey,
  SavingsAccountType,
} from "./enums.js";

// Types
export type {
  CopFixedRate,
  UvrSpreadRate,
  Rate,
  PayrollDiscount,
  OfferConditions,
  ExtractionInfo,
  OfferSource,
  MortgageOffer,
  RankingMetric,
  RankedEntry,
  ScenarioRanking,
  Rankings,
  MortgageOffersDataset,
  BankMortgageParseResult,
  // Savings types
  SavingsRate,
  SavingsSource,
  SavingsOffer,
  SavingsOffersDataset,
  BankSavingsParseResult,
} from "./types.js";

// Zod Schemas
export {
  BankIdSchema,
  MortgageTypeSchema,
  CurrencyIndexSchema,
  SegmentSchema,
  ChannelSchema,
  SourceTypeSchema,
  ExtractionMethodSchema,
  MortgageScenarioKeySchema,
  SavingsAccountTypeSchema,
  CopFixedRateSchema,
  UvrSpreadRateSchema,
  RateSchema,
  PayrollDiscountSchema,
  OfferConditionsSchema,
  ExtractionInfoSchema,
  OfferSourceSchema,
  MortgageOfferSchema,
  RankingMetricSchema,
  RankedEntrySchema,
  ScenarioRankingSchema,
  RankingsSchema,
  MortgageOffersDatasetSchema,
  BankMortgageParseResultSchema,
  // Savings schemas
  SavingsRateSchema,
  SavingsOfferSchema,
  SavingsOffersDatasetSchema,
  BankSavingsParseResultSchema,
} from "./schemas.js";
